name: Load RAG Database

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  load-rag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./backend
        run: bun install

      - name: Run RAG loader script
        working-directory: ./backend
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          DATABASE_URL_DEV: ${{ secrets.DATABASE_URL_DEV }}
          RAG_DATABASE_URL: ${{ secrets.RAG_DATABASE_URL }}
        run: bash scripts/loadRagDB.sh
