name: Sync with Upstream

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout forked repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_GITHUB }}

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/fractal-bootcamp/snack-safari.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Sync with upstream main branch
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
