name: Vercel Deployment Notifications

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep for 10 minutes
        run: sleep 600

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./backend
        run: bun install

      - name: Run Vercel notifications script
        working-directory: ./backend
        env:
          NODEMAILER_USER_EMAIL: ${{ secrets.NODEMAILER_USER_EMAIL }}
          NODEMAILER_USER_PASSWORD: ${{ secrets.NODEMAILER_USER_PASSWORD }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: bash scripts/vercelNotifications.sh
